_format_version: "2.1"

services:
  - name: auth-service
    url: http://172.23.0.6:9898
    routes:
      - name: sign-up
        paths:
          - /auth/v1/signup

  - name: user-service
    url: http://172.23.0.5:9797
    routes:
      - name: get-user
        paths:
          - /user/v1/getUser